INC_DIR = ../include
# GPP = g++-5
# GPP = /home/aditya/gcc-5.2.0-build/bin/g++-5.2
OPTIONS = -ggdb -std=c++11

insacs:
	$(GPP) insacs.cpp -o insacs.out $(OPTIONS) -I$(INC_DIR)

insib:
	$(GPP) insacsib.cpp -o insib.out $(OPTIONS) -I$(INC_DIR)

tinsac:
	$(GPP) tinsac.cpp -o tinsac.out $(OPTIONS) -I$(INC_DIR)

